### ISSUE TITLE
help/blocking-uris outdated paths

### ISSUE THREAD

**Issue by jidanni** [bitwarden/contributing-docs#348]
### Page

https://bitwarden.com/help/blocking-uris/

### Expected Result

We see
> In the Bitwarden Android app, open the  Settings tab.

>Tap Auto-fill.

>Tap Options.

Sorry. No such button.

> Scroll down to the bottom of the Options screen and enter URIs in the
> Auto-fill blocked URIs input. Blocked URIs should be specified in a
> comma-separated list, for example:

Sorry, no such exact lists there either.

P.S., I couldn't find the proper place to submit this bug report.

**Comment by djsmith85** [comment]
@jidanni Thank you for the report. I have passed the information on to the team. For future reports: At the bottom of every page in the Help-Center there is a `Make a suggestion to this page`-button. Any feedback there is monitored by our technical docs team.

**Comment by fschillingeriv** [comment]
Thanks for the report @jidanni! We've updated the page accordingly. As @djsmith85 mentioned, feedback is always appreciated and the **Make a suggestion** box will ensure the docs team sees it promptly.
